# Rendered by the Jenkins config generator from noahes/<environment>/env.properties.
MYSQL_HOST={{.MYSQL_HOST}}
MYSQL_PORT={{.MYSQL_PORT}}
MYSQL_USERNAME={{.MYSQL_USERNAME}}
MYSQL_PASSWORD={{.MYSQL_PASSWORD}}
MYSQL_DATABASE={{.MYSQL_DATABASE}}
MYSQL_TLS={{.MYSQL_TLS}}
MYSQL_CONNECT_TIMEOUT={{.MYSQL_CONNECT_TIMEOUT}}
MYSQL_READ_TIMEOUT={{.MYSQL_READ_TIMEOUT}}
MYSQL_WRITE_TIMEOUT={{.MYSQL_WRITE_TIMEOUT}}
